"""set class id to null is false in student model

Revision ID: 17a788810000
Revises: f40632dc76e1
Create Date: 2026-03-20 17:57:10.554182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a788810000'
down_revision: Union[str, Sequence[str], None] = 'f40632dc76e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
