"""removing full_name field from student tabe

Revision ID: 3dfe3a5f8df5
Revises: a826d717c1f7
Create Date: 2026-03-18 16:15:27.423021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfe3a5f8df5'
down_revision: Union[str, Sequence[str], None] = 'a826d717c1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
