"""added cascade to relations

Revision ID: 84a21560f973
Revises: f149d548dae6
Create Date: 2026-02-28 08:49:14.228000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a21560f973'
down_revision: Union[str, Sequence[str], None] = 'f149d548dae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('class_subjects_subject_id_fkey'), 'class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('class_subjects_class_id_fkey'), 'class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('class_subjects_teacher_id_fkey'), 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_subjects', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class_subjects', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('scores_class_subject_id_fkey'), 'scores', type_='foreignkey')
    op.drop_constraint(op.f('scores_student_id_fkey'), 'scores', type_='foreignkey')
    op.drop_constraint(op.f('scores_assessment_id_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'class_subjects', ['class_subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scores', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scores', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_class_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teachers_user_id_fkey'), 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('teachers_user_id_fkey'), 'teachers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_class_id_fkey'), 'students', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_assessment_id_fkey'), 'scores', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(op.f('scores_student_id_fkey'), 'scores', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('scores_class_subject_id_fkey'), 'scores', 'class_subjects', ['class_subject_id'], ['id'])
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('class_subjects_teacher_id_fkey'), 'class_subjects', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('class_subjects_class_id_fkey'), 'class_subjects', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(op.f('class_subjects_subject_id_fkey'), 'class_subjects', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
