"""empty message

Revision ID: a826d717c1f7
Revises: e841e10872ce
Create Date: 2026-03-18 14:06:39.636083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a826d717c1f7'
down_revision: Union[str, Sequence[str], None] = 'e841e10872ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.add_column('assessments', sa.Column('title', sa.String(), nullable=False))
    op.add_column('assessments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('class_subject_id', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('term', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('sequence', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('max_score', sa.Float(), nullable=False))
    op.add_column('assessments', sa.Column('date', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_assessments_name'), table_name='assessments')
    op.create_foreign_key(None, 'assessments', 'class_subjects', ['class_subject_id'], ['id'])
    op.drop_column('assessments', 'name')
    op.drop_column('assessments', 'weight_percentage')
    op.alter_column('classes', 'name',
               existing_type=postgresql.ENUM('FORM_1', 'FORM_2', 'FORM_3', 'FORM_4', 'FORM_5', 'LOWER_SIXTH', 'UPPER_SIXTH', name='classname'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scores', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scores', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint('_student_assessment_uc', 'scores', ['student_id', 'assessment_id'])
    op.create_index('idx_assessment_student', 'scores', ['assessment_id', 'student_id'], unique=False)
    op.drop_constraint(op.f('scores_class_subject_id_fkey'), 'scores', type_='foreignkey')
    op.drop_constraint(op.f('scores_assessment_id_fkey'), 'scores', type_='foreignkey')
    op.drop_constraint(op.f('scores_student_id_fkey'), 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'scores', 'assessments', ['assessment_id'], ['id'])
    op.drop_column('scores', 'term')
    op.drop_column('scores', 'class_subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('class_subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key(op.f('scores_student_id_fkey'), 'scores', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('scores_assessment_id_fkey'), 'scores', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('scores_class_subject_id_fkey'), 'scores', 'class_subjects', ['class_subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_assessment_student', table_name='scores')
    op.drop_constraint('_student_assessment_uc', 'scores', type_='unique')
    op.alter_column('scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('scores', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scores', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('classes', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FORM_1', 'FORM_2', 'FORM_3', 'FORM_4', 'FORM_5', 'LOWER_SIXTH', 'UPPER_SIXTH', name='classname'),
               existing_nullable=True)
    op.add_column('assessments', sa.Column('weight_percentage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('name', postgresql.ENUM('SEQUENCE1', 'EXAM', name='assessmentname'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_index(op.f('ix_assessments_name'), 'assessments', ['name'], unique=True)
    op.drop_column('assessments', 'date')
    op.drop_column('assessments', 'max_score')
    op.drop_column('assessments', 'sequence')
    op.drop_column('assessments', 'term')
    op.drop_column('assessments', 'class_subject_id')
    op.drop_column('assessments', 'description')
    op.drop_column('assessments', 'title')
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('results_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('results_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('results_pkey'))
    )
    # ### end Alembic commands ###
